dist: trusty
sudo: required
language: go

go_import_path: github.com/ligato/vpp-agent
git:
    depth: 5

go:
  - 1.9.x

cache:
  directories:
    - $HOME/build-cache

env:
  - GO_BUILD_TAGS=novpp

before_install:
  - go get -u -f github.com/alecthomas/gometalinter
  - gometalinter --install
  - go get github.com/mattn/goveralls
  - sudo apt-get update
  - sudo apt-get install npm && npm install -g markdown-link-check

script:
  - make check_links || true
  - make lint
  - make
  - make test-cover

after_success:
  - goveralls -coverprofile=/tmp/coverage.out -service=travis-ci
